-- =============================================================
-- init-databases.sql — Schema completo "Sanos y Salvos"
-- Ejecutar con: psql -h <RDS_HOST> -U sanosadmin -d postgres -f init-databases.sql
--
-- Distribución por base de datos:
--   auth_db          → roles, users, user_security_status, refresh_tokens
--   mascotas_db      → reporte_estados, mascotas, reportes
--   geolocalizacion_db → ubicaciones_reporte  (requiere PostGIS)
--   coincidencias_db → coincidencia_estados, coincidencias, coincidencia_scores (requiere pg_trgm)
--
-- Nota: las FKs cruzadas entre BDs no existen a nivel SQL — se manejan en la aplicación.
-- Hibernate (ddl-auto=update) crea las tablas al arrancar; este script sirve como
-- referencia de schema y para insertar datos de lookup (roles, estados).
-- =============================================================

-- =============================================
-- CREAR BASES DE DATOS (si no existen)
-- =============================================

SELECT 'CREATE DATABASE auth_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'auth_db') \gexec

SELECT 'CREATE DATABASE mascotas_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mascotas_db') \gexec

SELECT 'CREATE DATABASE geolocalizacion_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'geolocalizacion_db') \gexec

SELECT 'CREATE DATABASE coincidencias_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'coincidencias_db') \gexec

-- =============================================
-- AUTH_DB
-- =============================================
\c auth_db

CREATE TABLE IF NOT EXISTS roles (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id            uuid PRIMARY KEY,
  nombre        varchar(100) NOT NULL,
  email         varchar(150) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  rol_id        integer NOT NULL,
  created_at    timestamp DEFAULT now(),
  is_active     boolean DEFAULT true,
  CONSTRAINT fk_users_roles FOREIGN KEY (rol_id) REFERENCES roles(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS user_security_status (
  user_id                  uuid PRIMARY KEY,
  failed_attempts          integer DEFAULT 0,
  is_locked                boolean DEFAULT false,
  lock_expiry              timestamp,
  verification_token       varchar(255),
  verification_token_expiry timestamp,
  email_verified           boolean DEFAULT false,
  CONSTRAINT fk_security_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id         uuid PRIMARY KEY,
  token      varchar(255) UNIQUE NOT NULL,
  user_id    uuid NOT NULL,
  created_at timestamp DEFAULT now(),
  expires_at timestamp NOT NULL,
  CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- Datos iniciales de lookup
INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('USER')  ON CONFLICT DO NOTHING;

-- =============================================
-- MASCOTAS_DB
-- =============================================
\c mascotas_db

-- -------------------------------------------------------
-- CATÁLOGO: ESPECIES
-- Tabla normalizada — reemplaza varchar especie en reportes
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS especies (
  id     SERIAL PRIMARY KEY,
  nombre varchar(50) NOT NULL UNIQUE  -- "PERRO", "GATO", "AVE", "CONEJO", "OTRO"
);

-- -------------------------------------------------------
-- CATÁLOGO: RAZAS
-- Cada raza pertenece a una especie (FK)
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS razas (
  id         SERIAL PRIMARY KEY,
  especie_id integer NOT NULL,
  nombre     varchar(100) NOT NULL,
  CONSTRAINT fk_raza_especie FOREIGN KEY (especie_id) REFERENCES especies(id)
);

CREATE INDEX IF NOT EXISTS idx_razas_especie ON razas(especie_id);

-- -------------------------------------------------------
-- TABLA PRINCIPAL DE REPORTES (SINGLE TABLE INHERITANCE)
-- Hibernate crea y gestiona esta tabla automáticamente.
-- La tabla unifica PERDIDO + ENCONTRADO con discriminador 'tipo'.
-- especie_id y raza_id reemplazan las columnas varchar anteriores.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS reportes (
  id              uuid PRIMARY KEY,
  tipo            varchar(31) NOT NULL,       -- discriminador JPA: "PERDIDO" | "ENCONTRADO"
  user_id         uuid NOT NULL,             -- FK lógica → auth_db.users(id)
  especie_id      integer,                   -- FK → especies(id)
  raza_id         integer,                   -- FK → razas(id), nullable
  nombre          varchar(100),
  color           varchar(100),
  tamano          varchar(20),               -- enum: PEQUENO, MEDIANO, GRANDE
  descripcion     text,
  foto_url        varchar(512),
  estado          varchar(20) DEFAULT 'ACTIVO',  -- enum: ACTIVO, INACTIVO, RESUELTO
  lat             double precision,
  lng             double precision,
  direccion       varchar(500),
  fecha_evento    timestamp,
  -- Campos PERDIDO
  recompensa      numeric(38,2),
  -- Campos ENCONTRADO
  lugar_resguardo varchar(500),
  tiene_collar    boolean,
  created_at      timestamp DEFAULT now(),
  CONSTRAINT fk_reporte_especie FOREIGN KEY (especie_id) REFERENCES especies(id),
  CONSTRAINT fk_reporte_raza    FOREIGN KEY (raza_id)    REFERENCES razas(id)
);

CREATE INDEX IF NOT EXISTS idx_reportes_user_id    ON reportes(user_id);
CREATE INDEX IF NOT EXISTS idx_reportes_tipo        ON reportes(tipo);
CREATE INDEX IF NOT EXISTS idx_reportes_estado      ON reportes(estado);
CREATE INDEX IF NOT EXISTS idx_reportes_especie     ON reportes(especie_id);

-- -------------------------------------------------------
-- SEED DATA: ESPECIES (5 categorías base)
-- -------------------------------------------------------
INSERT INTO especies (nombre) VALUES
  ('PERRO'),
  ('GATO'),
  ('AVE'),
  ('CONEJO'),
  ('OTRO')
ON CONFLICT (nombre) DO NOTHING;

-- -------------------------------------------------------
-- SEED DATA: RAZAS
-- -------------------------------------------------------
-- Perros (especie_id = 1)
INSERT INTO razas (especie_id, nombre)
SELECT e.id, r.nombre
FROM especies e, (VALUES
  ('Labrador Retriever'),
  ('Golden Retriever'),
  ('Bulldog'),
  ('Pastor Alemán'),
  ('Poodle'),
  ('Chihuahua'),
  ('Beagle'),
  ('Boxer'),
  ('Dálmata'),
  ('Mestizo')
) AS r(nombre)
WHERE e.nombre = 'PERRO'
ON CONFLICT DO NOTHING;

-- Gatos (especie_id = 2)
INSERT INTO razas (especie_id, nombre)
SELECT e.id, r.nombre
FROM especies e, (VALUES
  ('Siamés'),
  ('Persa'),
  ('Angora'),
  ('Bengalí'),
  ('Maine Coon'),
  ('Mestizo')
) AS r(nombre)
WHERE e.nombre = 'GATO'
ON CONFLICT DO NOTHING;

-- Aves (especie_id = 3)
INSERT INTO razas (especie_id, nombre)
SELECT e.id, r.nombre
FROM especies e, (VALUES
  ('Loro'),
  ('Periquito'),
  ('Cacatúa'),
  ('Canario'),
  ('Otra')
) AS r(nombre)
WHERE e.nombre = 'AVE'
ON CONFLICT DO NOTHING;

-- =============================================
-- GEOLOCALIZACION_DB
-- =============================================
\c geolocalizacion_db

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS ubicaciones_reporte (
  id                    uuid PRIMARY KEY,
  reporte_id            uuid UNIQUE NOT NULL,  -- FK lógica → mascotas_db.reportes(id)
  lat                   double precision NOT NULL,
  lng                   double precision NOT NULL,
  direccion             varchar(500),
  direccion_geocodificada varchar(500),
  geocodificado         boolean DEFAULT false,
  cluster_id            integer,
  created_at            timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ubicaciones_reporte_id ON ubicaciones_reporte(reporte_id);
-- Índice espacial para consultas geográficas rápidas
CREATE INDEX IF NOT EXISTS idx_ubicaciones_geo ON ubicaciones_reporte USING GIST (
  ST_MakePoint(lng, lat)
);

-- =============================================
-- COINCIDENCIAS_DB
-- =============================================
\c coincidencias_db

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS coincidencia_estados (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(20)
);

CREATE TABLE IF NOT EXISTS coincidencias (
  id                   uuid PRIMARY KEY,
  reporte_perdido_id   uuid NOT NULL,    -- FK lógica → mascotas_db.reportes(id)
  reporte_encontrado_id uuid NOT NULL,   -- FK lógica → mascotas_db.reportes(id)
  distancia_km         double precision,
  estado_id            integer NOT NULL,
  score_total          double precision NOT NULL,
  notificado           boolean DEFAULT false,
  created_at           timestamp DEFAULT now(),
  CONSTRAINT fk_coincidencia_estado FOREIGN KEY (estado_id) REFERENCES coincidencia_estados(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX IF NOT EXISTS idx_coincidencias_perdido   ON coincidencias(reporte_perdido_id);
CREATE INDEX IF NOT EXISTS idx_coincidencias_encontrado ON coincidencias(reporte_encontrado_id);
CREATE INDEX IF NOT EXISTS idx_coincidencias_score      ON coincidencias(score_total DESC);

CREATE TABLE IF NOT EXISTS coincidencia_scores (
  coincidencia_id uuid PRIMARY KEY,
  score_color     double precision,
  score_geo       double precision,
  score_raza      double precision,
  score_tamano    double precision,
  CONSTRAINT fk_scores_coincidencia FOREIGN KEY (coincidencia_id) REFERENCES coincidencias(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- Datos iniciales de lookup
INSERT INTO coincidencia_estados (nombre) VALUES ('PENDIENTE')  ON CONFLICT DO NOTHING;
INSERT INTO coincidencia_estados (nombre) VALUES ('CONFIRMADA') ON CONFLICT DO NOTHING;
INSERT INTO coincidencia_estados (nombre) VALUES ('RECHAZADA')  ON CONFLICT DO NOTHING;

-- =============================================
-- VERIFICACION FINAL
-- =============================================
\c postgres
SELECT datname, pg_size_pretty(pg_database_size(datname)) AS size
FROM pg_database
WHERE datname IN ('auth_db','mascotas_db','geolocalizacion_db','coincidencias_db')
ORDER BY datname;
