-- =============================================================
-- init-databases.sql — Schema completo "Sanos y Salvos"
-- Ejecutar con: psql -h <RDS_HOST> -U sanosadmin -d postgres -f init-databases.sql
--
-- Distribución por base de datos:
--   auth_db          → roles, users, user_security_status, refresh_tokens
--   mascotas_db      → reporte_estados, mascotas, reportes
--   geolocalizacion_db → ubicaciones_reporte  (requiere PostGIS)
--   coincidencias_db → coincidencia_estados, coincidencias, coincidencia_scores (requiere pg_trgm)
--
-- Nota: las FKs cruzadas entre BDs no existen a nivel SQL — se manejan en la aplicación.
-- Hibernate (ddl-auto=update) crea las tablas al arrancar; este script sirve como
-- referencia de schema y para insertar datos de lookup (roles, estados).
-- =============================================================

-- =============================================
-- CREAR BASES DE DATOS (si no existen)
-- =============================================

SELECT 'CREATE DATABASE auth_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'auth_db') \gexec

SELECT 'CREATE DATABASE mascotas_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mascotas_db') \gexec

SELECT 'CREATE DATABASE geolocalizacion_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'geolocalizacion_db') \gexec

SELECT 'CREATE DATABASE coincidencias_db'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'coincidencias_db') \gexec

-- =============================================
-- AUTH_DB
-- =============================================
\c auth_db

CREATE TABLE IF NOT EXISTS roles (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id            uuid PRIMARY KEY,
  nombre        varchar(100) NOT NULL,
  email         varchar(150) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  rol_id        integer NOT NULL,
  created_at    timestamp DEFAULT now(),
  is_active     boolean DEFAULT true,
  CONSTRAINT fk_users_roles FOREIGN KEY (rol_id) REFERENCES roles(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS user_security_status (
  user_id                  uuid PRIMARY KEY,
  failed_attempts          integer DEFAULT 0,
  is_locked                boolean DEFAULT false,
  lock_expiry              timestamp,
  verification_token       varchar(255),
  verification_token_expiry timestamp,
  email_verified           boolean DEFAULT false,
  CONSTRAINT fk_security_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id         uuid PRIMARY KEY,
  token      varchar(255) UNIQUE NOT NULL,
  user_id    uuid NOT NULL,
  created_at timestamp DEFAULT now(),
  expires_at timestamp NOT NULL,
  CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- Datos iniciales de lookup
INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('USER')  ON CONFLICT DO NOTHING;

-- =============================================
-- MASCOTAS_DB
-- =============================================
\c mascotas_db

CREATE TABLE IF NOT EXISTS reporte_estados (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(20)
);

CREATE TABLE IF NOT EXISTS mascotas (
  id          uuid PRIMARY KEY,
  user_id     uuid NOT NULL,          -- FK lógica → auth_db.users (no enforced en SQL)
  nombre      varchar(100),
  especie     varchar(100) NOT NULL,
  raza        varchar(100),
  color       varchar(100),
  tamano      varchar(20),
  foto_url    varchar(255),
  tiene_collar boolean,
  created_at  timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mascotas_user_id ON mascotas(user_id);
CREATE INDEX IF NOT EXISTS idx_mascotas_especie  ON mascotas(especie);

CREATE TABLE IF NOT EXISTS reportes (
  id              uuid PRIMARY KEY,
  mascota_id      uuid,                -- FK lógica → mascotas(id)
  user_id         uuid NOT NULL,       -- FK lógica → auth_db.users(id)
  tipo            varchar(20),         -- PERDIDO | ENCONTRADO | AVISTAMIENTO
  estado_id       integer NOT NULL,
  descripcion     text,
  fecha_evento    timestamp,
  recompensa      numeric(38,2),
  lugar_resguardo varchar(500),
  created_at      timestamp DEFAULT now(),
  CONSTRAINT fk_reporte_mascota FOREIGN KEY (mascota_id) REFERENCES mascotas(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_reporte_estado  FOREIGN KEY (estado_id)  REFERENCES reporte_estados(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX IF NOT EXISTS idx_reportes_user_id    ON reportes(user_id);
CREATE INDEX IF NOT EXISTS idx_reportes_mascota_id ON reportes(mascota_id);
CREATE INDEX IF NOT EXISTS idx_reportes_tipo        ON reportes(tipo);
CREATE INDEX IF NOT EXISTS idx_reportes_estado      ON reportes(estado_id);

-- Datos iniciales de lookup
INSERT INTO reporte_estados (nombre) VALUES ('ACTIVO')     ON CONFLICT DO NOTHING;
INSERT INTO reporte_estados (nombre) VALUES ('EN_PROCESO') ON CONFLICT DO NOTHING;
INSERT INTO reporte_estados (nombre) VALUES ('CERRADO')    ON CONFLICT DO NOTHING;
INSERT INTO reporte_estados (nombre) VALUES ('RESUELTO')   ON CONFLICT DO NOTHING;

-- =============================================
-- GEOLOCALIZACION_DB
-- =============================================
\c geolocalizacion_db

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS ubicaciones_reporte (
  id                    uuid PRIMARY KEY,
  reporte_id            uuid UNIQUE NOT NULL,  -- FK lógica → mascotas_db.reportes(id)
  lat                   double precision NOT NULL,
  lng                   double precision NOT NULL,
  direccion             varchar(500),
  direccion_geocodificada varchar(500),
  geocodificado         boolean DEFAULT false,
  cluster_id            integer,
  created_at            timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ubicaciones_reporte_id ON ubicaciones_reporte(reporte_id);
-- Índice espacial para consultas geográficas rápidas
CREATE INDEX IF NOT EXISTS idx_ubicaciones_geo ON ubicaciones_reporte USING GIST (
  ST_MakePoint(lng, lat)
);

-- =============================================
-- COINCIDENCIAS_DB
-- =============================================
\c coincidencias_db

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS coincidencia_estados (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(20)
);

CREATE TABLE IF NOT EXISTS coincidencias (
  id                   uuid PRIMARY KEY,
  reporte_perdido_id   uuid NOT NULL,    -- FK lógica → mascotas_db.reportes(id)
  reporte_encontrado_id uuid NOT NULL,   -- FK lógica → mascotas_db.reportes(id)
  distancia_km         double precision,
  estado_id            integer NOT NULL,
  score_total          double precision NOT NULL,
  notificado           boolean DEFAULT false,
  created_at           timestamp DEFAULT now(),
  CONSTRAINT fk_coincidencia_estado FOREIGN KEY (estado_id) REFERENCES coincidencia_estados(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX IF NOT EXISTS idx_coincidencias_perdido   ON coincidencias(reporte_perdido_id);
CREATE INDEX IF NOT EXISTS idx_coincidencias_encontrado ON coincidencias(reporte_encontrado_id);
CREATE INDEX IF NOT EXISTS idx_coincidencias_score      ON coincidencias(score_total DESC);

CREATE TABLE IF NOT EXISTS coincidencia_scores (
  coincidencia_id uuid PRIMARY KEY,
  score_color     double precision,
  score_geo       double precision,
  score_raza      double precision,
  score_tamano    double precision,
  CONSTRAINT fk_scores_coincidencia FOREIGN KEY (coincidencia_id) REFERENCES coincidencias(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

-- Datos iniciales de lookup
INSERT INTO coincidencia_estados (nombre) VALUES ('PENDIENTE')  ON CONFLICT DO NOTHING;
INSERT INTO coincidencia_estados (nombre) VALUES ('CONFIRMADA') ON CONFLICT DO NOTHING;
INSERT INTO coincidencia_estados (nombre) VALUES ('RECHAZADA')  ON CONFLICT DO NOTHING;

-- =============================================
-- VERIFICACION FINAL
-- =============================================
\c postgres
SELECT datname, pg_size_pretty(pg_database_size(datname)) AS size
FROM pg_database
WHERE datname IN ('auth_db','mascotas_db','geolocalizacion_db','coincidencias_db')
ORDER BY datname;
