server:
  port: 8082

spring:
  application:
    name: ms-mascotas
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/mascotas_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

minio:
  endpoint: ${MINIO_ENDPOINT:https://s3.amazonaws.com}
  access-key: ${MINIO_ACCESS_KEY:}
  secret-key: ${MINIO_SECRET_KEY:}
  bucket: ${MINIO_BUCKET:sanos-y-salvos-mascotas-fotos}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

resilience4j:
  circuitbreaker:
    instances:
      rabbitmq:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.sanosysalvos: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
