server:
  port: 8083

spring:
  application:
    name: ms-geolocalizacion
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/geolocalizacion_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}

nominatim:
  base-url: https://nominatim.openstreetmap.org

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.sanosysalvos: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
